[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.config
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
known_first_party = ["app"]
multi_line_output = 3
include_trailing_comma = true
