"""creating heat association table

Revision ID: 781d22e1c1cb
Revises: 098bc38adff7
Create Date: 2020-03-29 10:00:08.190533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781d22e1c1cb'
down_revision = '098bc38adff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heat', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heat', 'status')
    # ### end Alembic commands ###
